### ISSUE TITLE
MapMyCells app taxonomy files

### ISSUE THREAD

**Issue by KatMedMed** [AllenInstitute/cell_type_mapper#12]
Hello, 

I would like to map my dataset to the taxonomies supported by MapMyCells (mouse brain). However, I am concerned about the security measures of uploading my research data to the app. Is it possible as an external user to get the HDF5 and json files to run the cell type mapping pipeline? 

Thank you

**Comment by danielsf** [comment]
We are discussing whether and how we want to make these files available.

While we're having that discussion, I'm going to go out on a limb and assume that you are the person who posted [this](https://community.brain-map.org/t/mapmycells-has-been-updated-with-new-data-algorithms-and-features/2777/2) comment to the forums. Does the response there alleviate your need/desire to run MapMyCells locally, or is this still an urgent issue for you?

**Comment by aladyeva-wustl** [comment]
Hi @danielsf!
I would also like to access taxonomy files that are used at the MapMyCells portal (mouse and human).
We are currently analyzing a large cohort of human samples and it will take too much time to do it through the web interface. Plus some of our input files are larger than the 500MB limit (just the count matrix itself).

Thank you!

**Comment by PolarBean** [comment]
Hi I would like to apply the cell taxonomy to a different problem that I have. How can I obtain the HDF5 file containing the average gene expression for each cluster. I can approximate this by averaging all the cells for each cluster in the shared WMB-10x datafiles but this is of course less optimal than using your original centroids :) May I ask what the concerns are regarding sharing this file publicly? The data you have provided is already of great use, thank you for this.

**Comment by danielsf** [comment]
@PolarBean @KatMedMed 

Sorry for the late (and arguably unhelpful) reply, but:

Do you mind posting your request (assuming access to these files is still something you are interested in) to the Allen Community Forum MapMyCells topic

https://community.brain-map.org/c/how-to/mapmycells/20

I think that might be the best place to get the answers you want. Issues on this repository are more for technical concerns with respect to the code itself. Your request isn't *techincally* about the cell type mapper code (though it admittedly exists in an obvious gray area).

**Comment by PolarBean** [comment]
Hey Daniel thanks for your response. I ended up just using the mean of each cell class and have moved on in my analysis. I can still post the request if it would be helpful to others.

**Comment by danielsf** [comment]
In case anyone is still waiting for this, we have made the files defining the on-line MapMyCells taxonomies available for download. Instructions for finding/downloading them are [on this page].(https://github.com/AllenInstitute/cell_type_mapper/blob/online/data/documentation/240812/docs/input_data_files/running_online_taxonomies_locally.md)

Please open a new issue if anything is unclear/unhelpful.
