### ISSUE TITLE
Specific marker genes for classes

### ISSUE THREAD

**Issue by mbatiuk** [AllenInstitute/cell_type_mapper#15]
Thanks for developing this nice tool, it is very useful to annotate our data with Allen taxonomy.

We got class/subclass predictions from mapmycells, and now we're trying to validate those with marker gene expression.

Currently, I am seeking information on marker genes that define each class and subclass in comparison to all others.

The MapMyCells website provides a .xlsm file, which seems to contain the desired information: [cl.df_CCN202307220.xlsx](https://allen-brain-cell-atlas.s3-us-west-2.amazonaws.com/metadata/WMB-taxonomy/20230830/cl.df_CCN202307220.xlsx).

Questions I have:

1. Can I accurately state that the columns "subclass.markers.combo" and "subclass.tf.markers.combo" contain the genes and transcription factors, respectively, that distinguish each **subclass** from all others?

2. I am struggling to locate the equivalent information (i.e., the set of marker genes) for the **class** level annotation. Is there a specific file or location where I can obtain this type of information?

Thank you for your assistance.

**Comment by danielsf** [comment]
Hi @mbatiuk ,

Your question falls in the weird political border between MapMyCells the algorithm and the reference taxonomies to which MapMyCells maps (in this case, the Whole Mouse Brain taxonomy). This repository is only watched by the people who implemented MapMyCells the algorithm. We accepted cell types and marker genes as an input from another team, who put together the spreadsheet you are referencing. I think you will get a more informative answer to your questions if you ask them in the Allen Brain Map Community Forum (which is watched by a broader set of Allen Institute scientists). I would recommend opening a new topic under this heading

https://community.brain-map.org/c/science/9

Good luck, and sorry I couldn't give you a more direct answer.

**Comment by mbatiuk** [comment]
Thanks for the response. I'll try asking on the forum then.
