### ISSUE TITLE
Is this the source codes behind MapMyCells?

### ISSUE THREAD

**Issue by beyondpie** [AllenInstitute/cell_type_mapper#24]
Hi there,

Thanks so much for releasing this package. Is this the backend of MapMyCells? 

Sincerely,
Songpeng

**Comment by danielsf** [comment]
With the exception of the Deep Generative Mapping algorithm for the SEA-AD taxonomy, which points to a different code base, yes: this is the backend of [MapMyCells](https://portal.brain-map.org/atlases-and-data/bkp/mapmycells)

**Comment by beyondpie** [comment]
@danielsf Thank you so much! That's what I need to understand how MapMyCells works in the backend. 

Songpeng
