### ISSUE TITLE
change in output information

### ISSUE THREAD

**Issue by mkunst23** [AllenInstitute/cell_type_mapper#3]
Hi,

I have a request for the simple correlation based mapping (flat mapping). In addition to the best correlated cell type per query cell with it's average correlation score, can you also output a list of the 25 next best cluster with it's associated correlation scores?

Thanks,
Michael

**Comment by danielsf** [comment]
@mkunst23 

I am finally getting around to addressing this issue.

My initial thought was to record the 25 "runner up" clusters and their average correlation coefficients in the extended output JSON file. This, however, would blow up that already large file from 2 GB to 16 GB (for the 4 million cell MERFISH data), so I think I may need to abandon my dream of an output JSON blob and accept the reality that we need to use a pandas dataframe written out to HDF5.

I have two schemes in mind. I've simulated examples here

```
/allen/aibs/technology/danielsf/knowledge_base/scratch/output_design
```

`many_df.h5` records each level of the taxonomy in a separate dataframe. In Python, you would get the dataframe of cluster assignments with
```
import pandas
cluster_df = pandas.read_hdf('many_df.h5', key='CCN20230504_CLUS')
```
Similarly, you would get the dataframe of subclass assignments with
```
subclass_df = pandas.read_hdf('many_df.h5', key='CCN20230504_SUBC')
```
etc. Each dataframe has the same columns. The runner up assignments are in columns named `runner_up_[0-25]` and the corresponding correlation coefficients are in `runner_up_[0-25]_cor` (please note that this data is all randomly generated; I just wanted to simulate the shape).

`single_df.h5` records all of the results at all taxonomic levels in a single dataframe. The columns a prefixed with the name of the taxonomic level, i.e.
```
CCN20230504_CLAS_assignment,
CCN20230504_CLAS_bootstrapping_probability,
...
CCN20230504_SUBC_assignment,
CCN20230504_SUBC_assignment,
...
```
The dataframe can be read in with
```
import pandas
df = pandas.read_hdf('single_df.h5', key='results')
```

I prefer the `many_df.h5` shape. I do not like prefixing the column names with the taxonomic level. I'm not a fan of long column names. Is there a shape you prefer (can either of these be easily accessed in R)?
